1911c1911,1919
<     test_anonymousSTOR ...                                                 [OK]
---
>     test_anonymousSTOR ... 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
> <DelayedCall 259672616 [599.99494791s] called=0 cancelled=0 FTP.__timedOut()>
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <ProtocolWrapper #0 on 45211>
> <<class 'twisted.internet.tcp.Port'> of twisted.protocols.ftp.DTPFactory on 54898>
2739a2748,2751
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <Echo #0 on 45611>
3002,3005c3014,3039
<     test_consumer ...                                                      [OK]
<     test_hostAndPeer ...                                                   [OK]
<     test_lastWriteReceived ...                                             [OK]
<     test_loseConnection ...                                                [OK]
---
>     test_consumer ...                                                   [ERROR]
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <twisted.internet.process.ProcessReader object at 0x14cac550>
> <twisted.internet.process.ProcessWriter object at 0x14cac490>
> <twisted.internet.process.ProcessReader object at 0x14cac5d0>
>     test_hostAndPeer ...                                                [ERROR]
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <twisted.internet.process.ProcessWriter object at 0x14cacb50>
> <twisted.internet.process.ProcessReader object at 0x14cacb90>
> <twisted.internet.process.ProcessReader object at 0x14cacbd0>
>     test_lastWriteReceived ...                                          [ERROR]
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <PTYProcess pid=9858 status=-1>
>     test_loseConnection ...                                             [ERROR]
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <twisted.internet.process.ProcessReader object at 0x14cb5e10>
> <twisted.internet.process.ProcessWriter object at 0x14cb5d90>
> <twisted.internet.process.ProcessReader object at 0x14cb5dd0>
3007,3008c3041,3054
<     test_write ...                                                         [OK]
<     test_writeSequence ...                                                 [OK]
---
>     test_write ...                                                      [ERROR]
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <twisted.internet.process.ProcessReader object at 0x14d57310>
> <twisted.internet.process.ProcessWriter object at 0x14d572d0>
> <twisted.internet.process.ProcessReader object at 0x14d573d0>
>     test_writeSequence ...                                              [ERROR]
> 
> /usr/local/lib/python2.5/site-packages/twisted/trial/reporter.py:215: exceptions.UserWarning: Reactor was unclean.
> Selectables:
> <twisted.internet.process.ProcessWriter object at 0x14d57610>
> <twisted.internet.process.ProcessReader object at 0x14d57650>
> <twisted.internet.process.ProcessReader object at 0x14d57690>
5032a5079,5108
> [ERROR]: twisted.test.test_stdio.StandardInputOutputTestCase.test_consumer
> 
> Traceback (most recent call last):
> Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_stdio.StandardInputOutputTestCase testMethod=test_consumer> (test_consumer) still running at 120.0 secs
> ===============================================================================
> [ERROR]: twisted.test.test_stdio.StandardInputOutputTestCase.test_hostAndPeer
> 
> Traceback (most recent call last):
> Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_stdio.StandardInputOutputTestCase testMethod=test_hostAndPeer> (test_hostAndPeer) still running at 120.0 secs
> ===============================================================================
> [ERROR]: twisted.test.test_stdio.StandardInputOutputTestCase.test_lastWriteReceived
> 
> Traceback (most recent call last):
> Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_stdio.StandardInputOutputTestCase testMethod=test_lastWriteReceived> (test_lastWriteReceived) still running at 120.0 secs
> ===============================================================================
> [ERROR]: twisted.test.test_stdio.StandardInputOutputTestCase.test_loseConnection
> 
> Traceback (most recent call last):
> Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_stdio.StandardInputOutputTestCase testMethod=test_loseConnection> (test_loseConnection) still running at 120.0 secs
> ===============================================================================
> [ERROR]: twisted.test.test_stdio.StandardInputOutputTestCase.test_write
> 
> Traceback (most recent call last):
> Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_stdio.StandardInputOutputTestCase testMethod=test_write> (test_write) still running at 120.0 secs
> ===============================================================================
> [ERROR]: twisted.test.test_stdio.StandardInputOutputTestCase.test_writeSequence
> 
> Traceback (most recent call last):
> Failure: twisted.internet.defer.TimeoutError: <twisted.test.test_stdio.StandardInputOutputTestCase testMethod=test_writeSequence> (test_writeSequence) still running at 120.0 secs
> ===============================================================================
5068c5144
< Ran 3552 tests in 187.365s
---
> Ran 3552 tests in 913.530s
5070c5146
< FAILED (skips=50, expectedFailures=17, failures=1, errors=9, successes=3476)
---
> FAILED (skips=50, expectedFailures=17, failures=1, errors=15, successes=3469)
